In [1]:
%cd ..

/common/wut4/workspace/scikit-rebate

In [2]:
import pandas as pd

In [3]:
genetic_data = pd.read_csv(
    'data/GAMETES_Epistasis_2-Way_20atts_0.4H_EDM-1_1.csv')

genetic_data_cont_endpoint = pd.read_csv(
    'data/GAMETES_Epistasis_2-Way_continuous_endpoint_a_20s_1600her_0.4__maf_0.2_EDM-2_01.csv')

genetic_data_mixed_attributes = pd.read_csv(
    'data/GAMETES_Epistasis_2-Way_mixed_attribute_a_20s_1600her_0.4__maf_0.2_EDM-2_01.csv')

genetic_data_missing_values = pd.read_csv(
    'data/GAMETES_Epistasis_2-Way_missing_values_0.1_a_20s_1600her_0.4__maf_0.2_EDM-2_01.csv')

genetic_data_multiclass = pd.read_csv('data/3Class_Datasets_Loc_2_01.csv')

In [5]:
print(len(genetic_data))
genetic_data.head()

1600

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,N11,N12,N13,N14,N15,N16,N17,P1,P2,class
0,0,0,2,1,1,0,0,2,0,1,...,2,1,0,0,0,0,0,0,1,1
1,0,0,1,0,0,1,1,0,0,1,...,0,1,0,0,0,0,0,0,0,1
2,0,0,0,1,0,2,0,0,0,0,...,1,1,0,0,2,2,0,0,0,1
3,0,1,0,2,0,1,0,2,0,0,...,1,1,0,1,1,0,1,1,0,1
4,0,0,1,1,0,0,0,1,1,0,...,1,0,0,1,0,0,1,1,0,1

In [6]:
print(len(genetic_data_cont_endpoint))
genetic_data_cont_endpoint.head()

1600

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,N11,N12,N13,N14,N15,N16,N17,M0P0,M0P1,class
0,0,1,0,1,1,2,0,1,0,0,...,1,2,1,2,2,1,0,0,2,1.153058
1,0,2,2,1,1,1,0,1,0,1,...,0,0,1,1,1,1,1,0,0,1.357748
2,0,2,2,1,2,1,0,1,0,1,...,0,0,2,0,0,1,0,0,0,0.808187
3,1,1,0,0,0,1,1,0,1,1,...,0,1,0,0,1,1,1,0,0,0.835353
4,0,1,1,0,0,0,0,1,0,0,...,1,0,0,0,0,1,0,0,0,0.275835

In [7]:
print(len(genetic_data_mixed_attributes))
genetic_data_mixed_attributes.head()

1600

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,N11,N12,N13,N14,N15,N16,N17,M0P0,M0P1,class
0,0,0,0,0,40.270326,0.403931,41.564082,2,37.935284,0,...,2,65.245733,2,1,25.715407,1,0,92.832123,56.182726,1
1,1,0,0,0,23.803000,81.968347,80.374806,1,5.728332,0,...,1,30.547434,1,1,22.890488,0,1,72.556568,63.969303,1
2,0,0,0,1,46.018482,31.025788,7.912649,2,35.496521,0,...,1,10.325026,1,1,30.555890,0,0,17.307370,43.374441,1
3,0,0,0,1,146.530853,4.704548,64.333634,0,37.356998,0,...,1,80.317533,1,1,77.496318,1,1,52.902681,73.830076,1
4,0,1,0,1,45.091603,5.889670,45.412836,0,34.892446,0,...,0,76.019258,1,1,16.544582,1,0,36.990813,43.779528,1

In [8]:
print(len(genetic_data_missing_values))
genetic_data_missing_values.head()

1600

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,N11,N12,N13,N14,N15,N16,N17,M0P0,M0P1,class
0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,NaN,0.0,...,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,1
1,1.0,0.0,1.0,0.0,0.0,1.0,1.0,NaN,1.0,0.0,...,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,NaN,1
2,2.0,0.0,NaN,1.0,2.0,0.0,2.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
4,0.0,NaN,NaN,0.0,NaN,0.0,1.0,1.0,0.0,NaN,...,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1

In [9]:
print(len(genetic_data_multiclass))
genetic_data_multiclass.head()

1600

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,N11,N12,N13,N14,N15,N16,N17,M0P0,M0P1,class
0,0,0,0,0,0,0,0,2,0,0,...,2,1,2,1,0,1,0,2,1,0
1,1,0,0,0,0,1,1,1,0,0,...,1,0,1,1,0,0,1,0,1,2
2,0,0,0,1,0,0,0,2,0,0,...,1,0,1,1,0,0,0,2,1,0
3,0,0,0,1,2,0,1,0,0,0,...,1,1,1,1,1,1,1,1,0,2
4,0,1,0,1,0,0,0,0,0,0,...,0,1,1,1,0,1,0,1,1,1

In [2]:
import pandas as pd
import numpy as np
from sklearn.pipeline import make_pipeline
from skrebate import ReliefF
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [3]:
genetic_data = pd.read_csv('./data/GAMETES_Epistasis_2-Way_continuous_endpoint_a_20s_1600her_0.4__maf_0.2_EDM-2_01.tsv.gz',
                           sep='\t', compression='gzip')
print(f'Total data size: {len(genetic_data)}')
genetic_data.head()

Total data size: 1600

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,N11,N12,N13,N14,N15,N16,N17,M0P0,M0P1,Class
0,0,1,0,1,1,2,0,1,0,0,...,1,2,1,2,2,1,0,0,2,1.153058
1,0,2,2,1,1,1,0,1,0,1,...,0,0,1,1,1,1,1,0,0,1.357748
2,0,2,2,1,2,1,0,1,0,1,...,0,0,2,0,0,1,0,0,0,0.808187
3,1,1,0,0,0,1,1,0,1,1,...,0,1,0,0,1,1,1,0,0,0.835353
4,0,1,1,0,0,0,0,1,0,0,...,1,0,0,0,0,1,0,0,0,0.275835

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
features, labels = genetic_data.drop('Class', axis=1).values, genetic_data['Class'].values

In [6]:
X_train, X_test, y_train, y_test = train_test_split(features, labels)
print(f'Training data: {len(X_train)}; Testing data: {len(X_test)}')

fs = ReliefF(n_features_to_select=2, n_neighbors=100)
fs.fit(X_train, y_train)

for feature_name, feature_score in zip(genetic_data.drop('Class', axis=1).columns,
                                       fs.feature_importances_):
    print(feature_name, '\t', feature_score)

Training data: 1200; Testing data: 400
N0 	 -0.00023786067420965035
N1 	 -0.0008344959181400399
N2 	 -0.00012957243549795587
N3 	 -0.0009587519395168307
N4 	 0.0007647651162532838
N5 	 0.0035500483183603486
N6 	 -0.0019153160383466726
N7 	 -0.0007283511516202821
N8 	 0.0016345453346324843
N9 	 -0.00020161834007815203
N10 	 0.002750524330711494
N11 	 0.0026534627522192497
N12 	 -1.6682677023010327e-06
N13 	 -0.0009991397287652127
N14 	 -0.003428192932657232
N15 	 0.0051871377177841495
N16 	 0.004149132367187451
N17 	 -0.0008130273071077734
M0P0 	 0.003261075579984118
M0P1 	 0.004261186184228512

In [8]:
X_train, X_test, y_train, y_test = train_test_split(features, labels)
print(f'Training data: {len(X_train)}; Testing data: {len(X_test)}')

fs = ReliefF(n_features_to_select=2, n_neighbors=100)
fs.fit(X_train, y_train)

summary = fs.summary()

for feature_name, data_type, feature_score in zip(genetic_data.drop('Class', axis=1).columns, summary['data type'],
                                       fs.feature_importances_):
    print(feature_name, '\t', data_type, '\t', feature_score)

Training data: 1200; Testing data: 400
N0 	 continuous 	 0.000727863848143252
N1 	 continuous 	 -0.0016743669319448852
N2 	 continuous 	 0.0018260418093048248
N3 	 continuous 	 -0.0004145876762478464
N4 	 continuous 	 0.0017035512643728808
N5 	 continuous 	 0.005296662917775775
N6 	 continuous 	 -0.0007636470134520472
N7 	 continuous 	 0.0015407063183105303
N8 	 continuous 	 0.001471570406908885
N9 	 continuous 	 -0.002220963802190439
N10 	 continuous 	 0.002740694352549334
N11 	 continuous 	 0.00248612937305448
N12 	 continuous 	 -0.0018351168451139484
N13 	 continuous 	 -0.0003471316194103908
N14 	 continuous 	 -0.0061195349016081755
N15 	 continuous 	 0.0004643676942537214
N16 	 continuous 	 0.00528721251766208
N17 	 continuous 	 0.0016599448444360257
M0P0 	 continuous 	 0.00392329712390056
M0P1 	 continuous 	 0.01424916948802696

In [9]:
genetic_data = pd.read_csv('./data/GAMETES_Epistasis_2-Way_missing_values_0.1_a_20s_1600her_0.4__maf_0.2_EDM-2_01.tsv.gz',
                           sep='\t', compression='gzip')
print(f'Total data size: {len(genetic_data)}')
genetic_data.head()

Total data size: 1600

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,N11,N12,N13,N14,N15,N16,N17,M0P0,M0P1,Class
0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,NaN,0.0,...,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,1
1,1.0,0.0,1.0,0.0,0.0,1.0,1.0,NaN,1.0,0.0,...,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,NaN,1
2,2.0,0.0,NaN,1.0,2.0,0.0,2.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
4,0.0,NaN,NaN,0.0,NaN,0.0,1.0,1.0,0.0,NaN,...,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1

In [14]:
genetic_data.max()

N0       2.0
N1       2.0
N2       2.0
N3       2.0
N4       2.0
N5       2.0
N6       2.0
N7       2.0
N8       2.0
N9       2.0
N10      2.0
N11      2.0
N12      2.0
N13      2.0
N14      2.0
N15      2.0
N16      2.0
N17      2.0
M0P0     2.0
M0P1     2.0
Class    1.0
dtype: float64

In [15]:
genetic_data = pd.read_csv('./data/GAMETES_Epistasis_2-Way_mixed_attribute_a_20s_1600her_0.4__maf_0.2_EDM-2_01.tsv.gz',
                           sep='\t', compression='gzip')
print(f'Total data size: {len(genetic_data)}')
genetic_data.head()

Total data size: 1600

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,N11,N12,N13,N14,N15,N16,N17,M0P0,M0P1,Class
0,0,0,0,0,40.270326,0.403931,41.564082,2,37.935284,0,...,2,65.245733,2,1,25.715407,1,0,92.832123,56.182726,1
1,1,0,0,0,23.803000,81.968347,80.374806,1,5.728332,0,...,1,30.547434,1,1,22.890488,0,1,72.556568,63.969303,1
2,0,0,0,1,46.018482,31.025788,7.912649,2,35.496521,0,...,1,10.325026,1,1,30.555890,0,0,17.307370,43.374441,1
3,0,0,0,1,146.530853,4.704548,64.333634,0,37.356998,0,...,1,80.317533,1,1,77.496318,1,1,52.902681,73.830076,1
4,0,1,0,1,45.091603,5.889670,45.412836,0,34.892446,0,...,0,76.019258,1,1,16.544582,1,0,36.990813,43.779528,1